### Create a new teacher
POST http://localhost:3000/teachers/signup
Content-Type: application/json

{


  "firstName": "John",
  "lastName": "Doe",
  "email": "john-doe@example.com",
  "address": "123 Main St",
  "city": "Anytown",
  "state": "Anystate",
  "yearsOfExperience": 5,
  "password": "12345"
}
### Get a teacher's profile by ID
GET http://localhost:3000/teachers/20/profile

### Delete a teacher by email
DELETE http://localhost:3000/teachers/john-doe@example.com

### Update Teacher Profile
PATCH http://localhost:3000/teacher/20/profile
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "phone": "123-456-7890",
  "address": "1234 Elm Street",
  "city": "Springfield",
  "state": "IL",
  "biography": "An experienced teacher with over 10 years in education...",
  "tiktokLink": "http://tiktok.com/@johndoe",
  "twitterLink": "http://twitter.com/johndoe",
  "facebookLink": "http://facebook.com/johndoe",
  "instagramLink": "http://instagram.com/johndoe"
}


### Login Request
POST http://localhost:3000/teachers/login
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "111"
}





